# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f56cc883b242f91a9acd5a6b2e32b3cb2814db33f5320c0e522cb174ffebfff7c75a8024c46db0e290d7477e7d37edb0ed88d6e23b8439adaae898e1d24a3eb2

test:
  secret_key_base: 3f3b9029a8f86ecba0750cbffc1f45060aff1d9a61a7e3de80eeb26262fef34246726e917415236dd38af0e680b84a58122a318459d2857f3a890ec3be90aa94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
